name: Bug report
description: Report a bug to help us improve the program
labels: [ bug ]
assignees: [ xf8b ]
body:
  - type: textarea
    attributes:
      label: Description
      description: What's the bug? How is it triggered? If you can, leave screenshots of the bug here as well.
      placeholder: |-
        For example:
        
        Bug: The program deletes all of my files
        
        How to Trigger:
        1. Start the program
        2. The bug happens
        
        Screenshots:
        [screenshot]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |-
        For example:
        
        I expected that my files would not be deleted.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows 10
        - Windows 11
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Program Version
      description: What program version are you using?
      placeholder: "For example: 1.6.9"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log File
      description: If you can, put the log of the program here.
      placeholder: |-
        Copy and paste the log file into here.
        This field is not required.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: Is there anything else you would like to say?
      placeholder: |-
        If you selected "Other" for your operating system, please say what it is here.
        This field is not required.
    validations:
      required: false