name: "Build"
on: [ push, pull_request ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          architecture: "x64"
      - name: "Build with Gradle"
        run: ./gradlew build